### ISSUE TITLE
[Suggestion] NativeMemory.

### ISSUE THREAD

**Issue by juliolitwin** [Molth/Kcp-CSharp#1]
Thank you for the project; it's interesting to finally see KCP implemented unmanaged in C#.

What do you think about replacing Marshal.AllocHGlobal() with NativeMemory.Alloc()? Of course, it might be necessary to check the .NET version, as only the more recent versions of .NET include NativeMemory, and since it is a newer library than Marshal, it might offer a slight performance boost.

Cheers.

**Comment by Molth** [comment]
I have added macro version checks in the project to use NativeMemory for newer versions and Marshal for older versions.
